### PR TITLE
Implement GitHub Actions

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
(as an updated copy of what Travis CI was doing)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Ping. @benoitc?

**Comment by benoitc** [comment]
sorry i'm slightly busy these days :). Thanks for the PR!

**Comment by benoitc** [comment]
This worked perfectly :)

**Comment by paulo-ferraz-oliveira** [comment]
Cool, thanks.

**Comment by benoitc** [comment]
i will tag it soon :) Thanks again!

**Pull request merged**
